[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pynecraft"
version = "1.0.0"
dependencies = [
  "titlecase",
]


[tool.setuptools]
packages = ["pynecraft"]
